export var foods=[
            {name:'egg',
            name_kor:'계란',
            img:'egg'},
            {name:'flour',
            name_kor:'밀가루',
            img:'flour'
            },
            {name:'milk',
            name_kor:'우유',
            img:'milk'
            },
            {name:'olive-oil',
            name_kor:'올리브오일',
            img:'olive-oil'
            },
            {name:'onion',
            name_kor:'양파',
            img:'onion'
            },
            {name:'potato',
            name_kor:'감자',
            img:'potato'
            },
            {name:'sugar',
            name_kor:'설탕',
            img:'sugar'
            },
            {name:'sweetpotato',
            name_kor:'고구마',
            img:'sweetpotato'
            },
            {name:'vanilla',
            name_kor:'바닐라빈',
            img:'vanilla'
            },
            {name:'pork',
            name_kor:'돼지고기',
            img:'pork'
            },
            {name:'shrimp',
            name_kor:'새우',
            img:'shrimp'
            },
            {name:'shrimp_saltsoup',
            name_kor:'새우젓',
            img:'shrimp'
            },
            {name:'beef',
            name_kor:'쇠고기',
            img:'beef'
            },
            {name:'pasta',
            name_kor:'파스타면',
            img:'pasta'
            },
            {name:'bacon',
            name_kor:'베이컨',
            img:'bacon'
            },
            {name:'bienna-sausage',
            name_kor:'비엔나소세지',
            img:'bienna-sausage'
            },
            {name:'sausage',
            name_kor:'소세지',
            img:'sausage'               
            },
            {name:'spring_onion',
            name_kor:'파',
            img:'spring_onion'               
            },
            {name:'garlic',
            name_kor:'마늘',
            img:'garlic'               
            },
            {name:'crushed_garlic',
            name_kor:'다진마늘',
            img:'garlic'               
            },
            {name:'salt',
            name_kor:'소금',
            img:'salt'               
            },
            {name:'black_pepper',
            name_kor:'후추',
            img:'black_pepper'               
            },
            {name:'ketchup',
            name_kor:'케찹',
            img:'season'               
            },
            {name:'oyster_sauce',
            name_kor:'굴소스',
            img:'season'               
            },
            {name:'carrot',
            name_kor:'당근',
            img:'carrot'               
            },
            {name:'dasida',
            name_kor:'다시다',
            img:'season'               
            },
            {name:'corn',
            name_kor:'옥수수',
            img:'corn'               
            },
            {name:'cheese',
            name_kor:'치즈',
            img:'cheese'               
            },
            {name:'rice',
            name_kor:'쌀',
            img:'rice'               
            },
            {name:'rice',
            name_kor:'찹쌀',
            img:'rice'               
            },
            {name:'bean',
            name_kor:'콩',
            img:'seed'               
            },
            {name:'green_bean',
            name_kor:'녹두',
            img:'seed'               
            },
            {name:'lettuce',
            name_kor:'상추',
            img:'lettuce'               
            },
            {name:'cabbage',
            name_kor:'배추',
            img:'cabbage'               
            },
            {name:'yang_cabbage',
            name_kor:'양배추',
            img:'yang_cabbage'               
            },
            {name:'spinach',
            name_kor:'시금치',
            img:'spinach' 
            },
            {name:'cucumber',
            name_kor:'오이',
            img:'cucumber' 
            },
            {name:'squash',
            name_kor:'애호박',
            img:'cucumber' 
            },
            {name:'pumpkin',
            name_kor:'호박',
            img:'pumpkin' 
            },
            {name:'tomato',
            name_kor:'토마토',
            img:'tomato' 
            },
            {name:'cherry_tomato',
            name_kor:'방울토마토',
            img:'tomato' 
            },
            {name:'radish',
            name_kor:'무',
            img:'radish' 
            },
            {name:'yeolmu',
            name_kor:'열무',
            img:'radish' 
            },
            {name:'dry_pepper',
            name_kor:'건고추',
            img:'pepper' 
            },
            {name:'put_pepper',
            name_kor:'풋고추',
            img:'pepper' 
            },
            {name:'ginger',
            name_kor:'생강',
            img:'ginger' 
            },
            {name:'pepper_powder',
            name_kor:'고춧가루',
            img:'pepper' 
            },
            {name:'jonmat_leaf',
            name_kor:'깻잎',
            img:'spinach' 
            },
            {name:'minari',
            name_kor:'미나리',
            img:'spinach' 
            },
            {name:'peanut',
            name_kor:'땅콩',
            img:'seed' 
            },
            {name:'nutari_mushroom',
            name_kor:'느타리버섯',
            img:'mushroom' 
            },
            {name:'pange_mushroom',
            name_kor:'팽이버섯',
            img:'mushroom' 
            },
            {name:'newsonge_mushroom',
            name_kor:'새송이버섯',
            img:'mushroom' 
            },
            {name:'jonmat_leaf',
            name_kor:'깻잎',
            img:'spinach' 
            },
            {name:'butter',
            name_kor:'버터',
            img:'butter'
            },
            {name:'honey',
            name_kor:'꿀',
            img:'honey'
            },

]