export var foods=[
            {name:'egg',
            name_kor:'계란',
            img:'egg'},
            {name:'flour',
            name_kor:'밀가루',
            img:'flour'
            },
            {name:'milk',
            name_kor:'우유',
            img:'milk'
            },
            {name:'olive-oil',
            name_kor:'올리브오일',
            img:'olive-oil'
            },
            {name:'onion',
            name_kor:'양파',
            img:'onion'
            },
            {name:'potato',
            name_kor:'감자',
            img:'potato'
            },
            {name:'sugar',
            name_kor:'설탕',
            img:'sugar'
            },
            {name:'sweetpotato',
            name_kor:'고구마',
            img:'sweetpotato'
            },
            {name:'vanilla',
            name_kor:'바닐라빈',
            img:'vanilla'
            },
            {name:'pork',
            name_kor:'돼지고기',
            img:'pork'
            },
            {name:'shrimp',
            name_kor:'새우',
            img:'shrimp'
            },
            {name:'beef',
            name_kor:'소고기',
            img:'beef'
            },
            {name:'pasta',
            name_kor:'파스타면',
            img:'pasta'
            },
            {name:'bacon',
            name_kor:'베이컨',
            img:'bacon'
            },
            {name:'bienna-sausage',
            name_kor:'비엔나소세지',
            img:'bienna-sausage'
            },
            {name:'sausage',
            name_kor:'소세지',
            img:'sausage'               
            },
            {name:'spring_onion',
            name_kor:'파',
            img:'spring_onion'               
            },
            {name:'garlic',
            name_kor:'마늘',
            img:'garlic'               
            },
            {name:'crushed_garlic',
            name_kor:'다진마늘',
            img:'garlic'               
            },
            {name:'salt',
            name_kor:'소금',
            img:'salt'               
            },
            {name:'black_pepper',
            name_kor:'후추',
            img:'black_pepper'               
            },
            {name:'ketchup',
            name_kor:'케찹',
            img:'season'               
            },
            {name:'oyster_sauce',
            name_kor:'굴소스',
            img:'season'               
            },
            {name:'carrot',
            name_kor:'당근',
            img:'carrot'               
            },
            {name:'dasida',
            name_kor:'다시다',
            img:'season'               
            },
            {name:'corn',
            name_kor:'옥수수',
            img:'corn'               
            },
            {name:'cheese',
            name_kor:'치즈',
            img:'cheese'               
            }

]